### ISSUE TITLE
Don't attempt to re-index archives that have 0 files in them

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#21]
If we encounter an archive with 0 files in it, we should add an entry to the db with a special file name like "EMPTY_ARCHIVE" so that summershum-cli doesn't keep trying to check it.

**Comment by pypingou** [comment]
For the few cases I have seen, the 0 files archives were due to bugs/missing pieces in our code, so as we improve it, it might be good that summershum-cli retrieves to import them.

**Comment by ralphbean** [comment]
> For the few cases I have seen, the 0 files archives were due to bugs/missing pieces in our code, so as we improve it, it might be good that summershum-cli retrieves to import them.

Agreed.  Closing as WONTFIX.
