### ISSUE TITLE
Don't attempt to re-download tarballs that are already in the db

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#22]
We can use the md5sum from datagrepper to check before downloading.  this will save a _ton_ of time on subsequent summershum-cli runs.

**Comment by pypingou** [comment]
Isn't this already in now?

**Comment by ralphbean** [comment]
Oh, that's true.  https://github.com/fedora-infra/summershum/blob/develop/summershum/core.py#L15-L19

My mistake.
