### ISSUE TITLE
Employ fedmsg msg_ids

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#24]
RFE, in two parts:
- when ingesting, summershum should print out (log) the msg_id of the fedmsg
  message that triggered it (whether it is the consumer, or the cli.. so add
  this in core.py:ingest)
- summershum-cli should optionally take a --msg-id argument that will cause it
  to request just that one message and try it again

**Comment by pypingou** [comment]
This addresses the first part https://github.com/fedora-infra/summershum/pull/26

**Comment by pypingou** [comment]
Second part should be addressed in https://github.com/fedora-infra/summershum/pull/27

**Comment by pypingou** [comment]
So this is fixed now :)
