### ISSUE TITLE
summershum-cli seems not work

### ISSUE THREAD

**Issue by brickgao** [fedora-infra/summershum#32]
when I run `summershum-cli` in the terminal, there throw out an error.

``` bash
Traceback (most recent call last):
  File "/usr/bin/summershum-cli", line 9, in <module>
    load_entry_point('summershum==0.1.5', 'console_scripts', 'summershum-cli')()
  File "/usr/lib/python2.7/site-packages/summershum-0.1.5-py2.7.egg/summershum/cli.py", line 82, in main
    dictConfig(config.get('logging', {'version': 1}))
  File "/usr/lib/python2.7/logging/config.py", line 803, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 509, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version
```

The dict for dictConfig should have a key named `version`, but there isn't an key named `version` in dict.

I use `fedmsg.d/example-config.py` as my config and `Python27`, `Archlinux` as my envrionment.

**Comment by pypingou** [comment]
Sounds like a nice task for one of our GSoC candidates :)

**Comment by ralphbean** [comment]
As a workaround, you can just `sudo yum install fedmsg` and this should work.

The patch in #33 is the right long-term fix, though.

**Comment by brickgao** [comment]
I get it and I use `fedmsg` which fetch from the dev branch now, thanks.

And I find `fedmsg` in `pip` maybe out of time. If I use `pip` to install fedmsg, there maybe throw out some error (sometime it  can't find the console handler). I think it should be updated ;)
